services:
  spark-master:
    image: spark-with-kafka
    container_name: spark-master
    command: bash -c "/opt/spark/sbin/start-master.sh && tail -f /opt/spark/logs/*"
    ports:
      - "7077:7077"
      - "8083:8080"
    networks:
      - airflow-spark
    volumes:
      - ./pyspark_instancia_pruebas:/opt/spark/app

  spark-worker:
    image: spark-with-kafka
    container_name: spark-worker
    command: bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark/logs/*"
    depends_on:
      - spark-master
    ports:
      - "8084:8081"
    networks:
      - airflow-spark
    volumes:
      - ./pyspark_instancia_pruebas:/opt/spark/app

  spark-client:
    image: spark-with-kafka
    container_name: spark-client
    depends_on:
      - spark-master
    stdin_open: true
    tty: true
    command: bash -lc "sleep infinity"
    networks:
      - airflow-spark
    volumes:
      - ./pyspark_instancia_pruebas:/opt/spark/app

networks:
  airflow-spark:
    external: true
